### ISSUE TITLE
Freezing pokemon-colorscripts source repo at a known commit

### ISSUE THREAD

**Issue by Adithyan-KV** [dbednar230/mon#1]
Hey, 

Creator of pokemon-colorscripts here. I love this program you've made.

As of now it seems like you are sourcing the colorscript files from the main branch of the gitlab repo for pokemon-colorscripts. So I believe any changes to the files in the main branch could break your script (for example ,I was considering compressing the text files in the source repo so that the files have a lower download size. If I do that, the .txt files being sourced in the script right now will not exist on the latest version on the main branch anymore, which could break the program) . 

So may I suggest sourcing the files from a known commit of the  source repo so as to be robust to future changes to the source?

**Comment by dbednar230** [comment]
> I was considering compressing the text files
> The .txt files being sourced in the script right now will not exist

Are you changing what's inside the text file or the name of the text file itself? As long as the name of the file does not change what it currently is should be fine (sourcing from main will also allow some amount of future proofing as long as new colorscripts get added with each generation).

Eventually there will probably be a better method of requesting the colorscripts rather than getting them directly anyways...

**Comment by Adithyan-KV** [comment]
Yeah so like I'll only store the text files in their compressed form. So the filenames will no longer be the same. It'll be 

> pokemon_name.txt.gz

or something like that. But the present filenames will always exists at the commit which the code is frozen at. 

And yeah some method of requesting the colorscripts rather than just fetching them directly would be the eventual best solution.

**Comment by dbednar230** [comment]
One thing: why not store the compressed data in the .txt file itself, removing the need for the .gz? Once you unpack the gz data it's going to take up the same amount of space

**Comment by Adithyan-KV** [comment]
Oh that's just some implementation details of the pokemon-colorscripts program. Like I was thinking of just printing out the data to the terminal leaving the source files unchanged, Using `gunzip -c` or whatever.

And the compression case was just an example. Didn't want your script to break just because I changed the directory structure or something. But yeah you do have a point that basing it on the latest main branch commit gives some future proofing if new generations are added.

**Comment by dbednar230** [comment]
> And yeah some method of requesting the colorscripts rather than just fetching them directly would be the eventual best solution.

[Found it!](https://docs.gitlab.com/ee/api/#file-path-branches-and-tags-name-encoding)
