### ISSUE TITLE
`mon` by itself no longer picks a random Pokemon

### ISSUE THREAD

**Issue by Maverick0089** [dbednar230/mon#4]
As of the latest update (0.3.0), `mon` by itself no longer picks a random Pokemon and appears to do nothing. However, specifying one still works. I've also noticed the string that appears above the expected result. 

See the screenshot below.
![image](https://user-images.githubusercontent.com/29494351/132953102-d6969263-e50e-48c5-9b4b-2d26aa17e16c.png)

**Comment by dbednar230** [comment]
[Fixed](https://github.com/dbednar230/mon/commit/bea392bfcd1453da2975c14cb706787e7b86eada)
