### ISSUE TITLE
"Height" and "Weight" labels are dark on transparent and dark backgrounds

### ISSUE THREAD

**Issue by Maverick0089** [dbednar230/mon#6]
![image](https://user-images.githubusercontent.com/29494351/140654338-fe17b0d2-beb7-421f-97a8-61663766ee5f.png)

See the image above. The labels for height and weight are almost unreadable on a dark or transparent terminal background. Tested on both a newly opened terminal and on a running one.

**Comment by dbednar230** [comment]
0.4 binaries will be updated soon
